Tarea de clase 5,  jorge_leonel
julian-vargas-kambcode/modulo3-kambcode pull request #45
Opened 2024-04-18 07:11 UTC by jorleo021978

Tarea 1 y 2 Algiritmos en codigo, descuento  en ventas por cantidades en peso,  Numeros primos.

2024-04-18 20:32 UTC, jorleo021978 commented
Profe actualice el diagrama.

2024-04-19 20:33 UTC, julian-vargas-kambcode requested changes
Hola Jorge, buenas tardes.

TE felicito lograste un buen trabajo, la corrección sobre el diagrama bien lograda ya tiene una buen forma para trabajarse, frente a la tarea 5 bien resuelto el primer punto lo hiciste bien y lograste interpretar correctamtne el proceso, felicidades.

EN el punto 2 no estas cumpliendo con lo solicitado, la idea es identificar si el numero que el usuario ingresa es un numero primo o no sin importar el valor, no lo que estas haciendo respecto a los numeros primos, voy a dejar el PR abierto para que puedas corregir ese punto 2

2024-04-22 21:52 UTC, julian-vargas-kambcode commented on jorge_tonguino_87453688/clase_5/usuarioIngresaNumer.js
Buen trabajo con la corrección

2024-04-22 21:54 UTC, julian-vargas-kambcode commented on jorge_tonguino_87453688/clase_6/Bucle_For_con_Arrays.js
buen trabajo, buen uso de la teoría

2024-04-22 21:55 UTC, julian-vargas-kambcode commented on jorge_tonguino_87453688/clase_6/buscacandoElLibro.js
Excelente trabajo, bien resutlto, tambien puedes explorar como resolverlos con indexOf o con search

2024-04-22 21:57 UTC, julian-vargas-kambcode commented on jorge_tonguino_87453688/clase_6/busquedaDeArrayEnObjetos.js
Excelente trabajo resuleto correctamente

2024-04-22 21:57 UTC, julian-vargas-kambcode commented on jorge_tonguino_87453688/clase_6/concatenationDeArray.js
Bien resuelto

2024-04-22 21:58 UTC, julian-vargas-kambcode commented on jorge_tonguino_87453688/clase_6/incrementoDeEdad.js
Excelente trabajo bien logrado

2024-04-22 21:59 UTC, julian-vargas-kambcode approved these changes
Excelente trabajo, se aprueban tareas 5 y 6, muy bien hecho se ve bastante dedicación en lo que haces, continua así, muy bien logrado.

2024-04-22 21:59 UTC, merged

2024-04-23 07:06 UTC, jorleo021978 commented
Muchas Gracias profe me adapte a su forma de enseñanza.

El lun, 22 abr 2024 a las 17:00, julian-vargas-kambcode (<
***@***.***>) escribió:

> Merged #45
> <https://github.com/julian-vargas-kambcode/modulo3-kambcode/pull/45> into
> main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/julian-vargas-kambcode/modulo3-kambcode/pull/45#event-12566270431>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BGW2P6G6B3IIQVMOLND7OA3Y6WB67AVCNFSM6AAAAABGMVO4X6VHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJSGU3DMMRXGA2DGMI>
> .
> You are receiving this because you authored the thread.Message ID:
> <julian-vargas-kambcode/modulo3-kambcode/pull/45/issue_event/12566270431@
> github.com>
>