tarea-4
julian-vargas-kambcode/modulo3-kambcode pull request #47
Opened 2024-04-19 01:16 UTC by Claudiadiazg

![Captura](https://github.com/julian-vargas-kambcode/modulo3-kambcode/assets/144074982/786c659d-f202-40af-b7a6-ceee6136ae02)

2024-04-19 02:04 UTC, Claudiadiazg commented
![Captura1](https://github.com/julian-vargas-kambcode/modulo3-kambcode/assets/144074982/615375de-c86b-4ff3-b08b-12625452b5ec)

2024-04-19 02:05 UTC, Claudiadiazg commented
segundo diagrama

2024-04-19 20:46 UTC, julian-vargas-kambcode requested changes
Hola Claudia, gracias por compartir tu trabajo.

TE felicito bien logrado en general, sin embargo en el diagrama del area del traingulo, deberias ajusta la parte de la ejecución de la formula, si quieres validar si el resultado es correcto, deberias poner despues del proceso la pregunta de si es correcto muestre y finalice si algo falla retorne a pedir los datos, por ejemplo, en el otro diagrama, no olvides etiquetas los caminos de si/no cuando haces una pregunta. Dejo el PR abierto para que puedas ajustar.

¡Saludos!

2024-04-22 22:13 UTC, julian-vargas-kambcode approved these changes
Se realiza el cierre del PR bajo lo entregado y se acepta tarea 4, por favor avanzar con las sigueitnes tareas

2024-04-22 22:14 UTC, merged