Oswaldo mendez 1127060867
julian-vargas-kambcode/modulo3-kambcode pull request #48
Opened 2024-04-19 04:25 UTC by oswaldo-mendez

un cordial saludo profe, me hubiese encantado tener el tiempo para hacer del trabajo opcional el diagrama de flujo pero no cuento con este. Gracias por la atención.

2024-04-19 20:55 UTC, julian-vargas-kambcode requested changes
Hola oswaldo, buenas tardes.

Gracias por compartir tu trabajo, en general bien resuelto, va entendiendo los flujos y representándolos en código, sin embargo, te dejo comentarios en el del calculo del descuento, la idea es que los datos sean ingresados por el usuario, reusa la libreria que usaste en el punto de numeros primos para esta parte, cuando vas a calcular descuento, los validadores del rango de precio es decir tods lso if/eseif que hiciste deberían estar igual dentro de la función calcular descuento para que tu codigo este bien implementado, dejo el PR abierto para uqe puedas realziar las correcciones.

2024-04-19 20:55 UTC, julian-vargas-kambcode commented on oswaldo-mendez-1127060867/tareaclase5/actividad1.js
por favor ajusta lo solicitado.

2024-04-20 01:21 UTC, oswaldo-mendez commented on oswaldo-mendez-1127060867/tareaclase5/actividad1.js
profesor ya realice las modificaciones recomendadas por favor revisar

2024-04-21 23:32 UTC, oswaldo-mendez commented on oswaldo-mendez-1127060867/tareaclase5/actividad1.js
profesor Julián también esta la actividad opcional de la clase 6 en este PR

2024-04-22 22:16 UTC, julian-vargas-kambcode commented on oswaldo-mendez-1127060867/tareaclase5/actividad1.js
Gracias oswaldo recibido el ajuste bien logrado

2024-04-22 22:17 UTC, julian-vargas-kambcode commented on oswaldo-mendez-1127060867/tareaopcionalclase6/buscarMenor.js
Bien resuelto, podrias mejorar el resultado trabajando con el objeto completo para evitar crear vaaribales adicionales como la del indicador

2024-04-22 22:18 UTC, julian-vargas-kambcode commented on oswaldo-mendez-1127060867/tareaopcionalclase6/buscarPalabra.js
Bien resulto podrias explorar otras opciones como includes o search para que las conozcas.

2024-04-22 22:19 UTC, julian-vargas-kambcode commented on oswaldo-mendez-1127060867/tareaopcionalclase6/cicloMultiplicar.js
Buena solución, podiras revisar el metodo push, para simplificar tu codigo y hacer uso de las propiedades de los array

2024-04-22 22:19 UTC, julian-vargas-kambcode commented on oswaldo-mendez-1127060867/tareaopcionalclase6/concatenarCadenas.js
Bien resuelto

2024-04-22 22:20 UTC, julian-vargas-kambcode commented on oswaldo-mendez-1127060867/tareaopcionalclase6/incrementarEdad.js
Bien resulto podrias haber usado ++ para la suma tambien puede validarlo.

2024-04-22 22:21 UTC, julian-vargas-kambcode approved these changes
Se apruebas las tareas 5 y 6, puedes revisar lso comentarios para qeu practiques cosas adicionales.

2024-04-22 22:21 UTC, merged