tareas 4 y 5 a la fecha
julian-vargas-kambcode/modulo3-kambcode pull request #50
Opened 2024-04-20 02:11 UTC by Cairon29

Aun falta la parte opcional de la tarea numero 5, sin embargo un avance es un avance.

2024-04-22 22:41 UTC, julian-vargas-kambcode requested changes
Hola bien hehco ne la tarea 6 te deje algunos comentarios para que puedas revisar y practicarlo, pero en general bien hecho. 

EN la tarea 5 si es necesario que realices lso ajustes necesarios, te dejo el PR abierto para qeu corrijas la tarea5.

¡saludos!

2024-04-22 22:41 UTC, julian-vargas-kambcode commented on Jose_Junco_1019762728/hw_05/actividad1.js
HOla Jose, bueno frente a este punto de la tarea, necesitas ajustar varios puntos, si estas llamando la función debes enviar los parámetros para que sean procesados, por otro lado se pide imprimir el precio final y la formula que escribiste no es correcta de acuerdo a lo que describe el diagrama, ajustala para que funcione correctamente e intenta realizar la captura de datos en linea

2024-04-22 22:41 UTC, julian-vargas-kambcode commented on Jose_Junco_1019762728/hw_06/main.js
Felicidades, bien resuelto, para la busqueda igual podrias usar metodos como include, search o indexof sin embargo es una opción viable, lo uncio es qeu no controlas el tamaño del arreglo cuando buscas en la letra siguiente si es la "l" podrias ya estar en la ultima posición y la siguiente no existir.

2024-04-28 18:46 UTC, Cairon29 commented on Jose_Junco_1019762728/hw_05/actividad1.js
Listo, ya he hecho la actualizacion de los puntos a resaltar. El archivo final se encuentra en el ultimo PR propuesto.

2024-04-29 22:14 UTC, julian-vargas-kambcode approved these changes
BIen logrado Jose felicidades, buen uso de la teoría, continua practicando.

¡Saludos!

2024-04-29 22:14 UTC, merged