Tareas_clase_7_Jorge_Tonguino
julian-vargas-kambcode/modulo3-kambcode pull request #55
Opened 2024-04-23 07:02 UTC by jorleo021978

Profe perdone la hora, aqui le cargo las tareas estare pendiente a cualquier requerimiento para el trabajo quede aprobado.

2024-04-24 23:28 UTC, julian-vargas-kambcode requested changes
Hola Jorge, gracias por el envío de tu tarea, bien hehco te felicito bien logrado, en tu commit se te fue la caprtea trabajos, creo que no corresponde a lo que es la solución de las tareas, entonces porfavor eliminala para que no se te suba eso dentro de tu carpeta o si la quieres subir me confirmas y apruebo el PR, por lo demas bien solucionado

2024-04-25 06:28 UTC, jorleo021978 commented
Buenos dias aqui le comparto mis tareas para que por faor mr las revice muchas gracias.

2024-04-26 19:58 UTC, julian-vargas-kambcode approved these changes
Hola Jorge, muy buen trabajo lo resolviste todo correctamente, muy bien hecho.

¡Saludos!

2024-04-26 19:58 UTC, merged

2024-04-26 20:29 UTC, jorleo021978 commented
Si profe es una carpeta donde hago las pruebas de cada trabajo y hay
algunas que me gustan las guardo para reforzar conocimientos.

El vie, 26 de abr de 2024, 2:58 p. m., julian-vargas-kambcode <
***@***.***> escribió:

> Merged #55
> <https://github.com/julian-vargas-kambcode/modulo3-kambcode/pull/55> into
> main.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/julian-vargas-kambcode/modulo3-kambcode/pull/55#event-12627973885>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BGW2P6EO7KXPJLTJGMDA2Y3Y7KWX7AVCNFSM6AAAAABGUHI6TOVHI2DSMVQWIX3LMV45UABCJFZXG5LFIV3GK3TUJZXXI2LGNFRWC5DJN5XDWMJSGYZDOOJXGM4DQNI>
> .
> You are receiving this because you authored the thread.Message ID:
> <julian-vargas-kambcode/modulo3-kambcode/pull/55/issue_event/12627973885@
> github.com>
>