Jorge tonguino 87453688
julian-vargas-kambcode/modulo3-kambcode pull request #68
Opened 2024-04-30 03:58 UTC by jorleo021978

profe este pull request es para actualizar carpetas.

2024-05-02 23:07 UTC, julian-vargas-kambcode requested changes
Hola Jorge, gracias por compartir tus tareas sin embargo varias cosa:
1) No se debe cargar la carpeta node_modules porqeu hace qeu sea muy dificl la revisión y finalmente no es algo que se versione.
2) en el archivo index.js hiciste un buen intento, falta trabajar mas para terminar la tarea correctamente.
3) en los archivos donde usaste async/await sería el adelanto de la tarea 11, sin embargo la tarea 10 no esta funcional, debes revisarla y ajustarla para resolverla correctamente.

2024-05-03 03:55 UTC, jorleo021978 commented
profe me comfirmas si se quito las carpetas por favor

2024-05-03 05:50 UTC, jorleo021978 commented
gracias por la corrección Profe estamos para aprender ya le cargue el otro
archivo.

El jue, 2 may 2024 a las 18:07, julian-vargas-kambcode (<
***@***.***>) escribió:

> ***@***.**** requested changes on this pull request.
>
> Hola Jorge, gracias por compartir tus tareas sin embargo varias cosa:
>
>    1. No se debe cargar la carpeta node_modules porqeu hace qeu sea muy
>    dificl la revisión y finalmente no es algo que se versione.
>    2. en el archivo index.js hiciste un buen intento, falta trabajar mas
>    para terminar la tarea correctamente.
>    3. en los archivos donde usaste async/await sería el adelanto de la
>    tarea 11, sin embargo la tarea 10 no esta funcional, debes revisarla y
>    ajustarla para resolverla correctamente.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/julian-vargas-kambcode/modulo3-kambcode/pull/68#pullrequestreview-2037100533>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/BGW2P6CQKQP67MZLUMRM6XTZALBMZAVCNFSM6AAAAABG7PARI6VHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDAMZXGEYDANJTGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***
> com>
>

2024-05-06 17:14 UTC, julian-vargas-kambcode approved these changes
Hola Jorge.

Felicidades, buen trabajo, bien resulto corregiste lo solicitado y buen  manejo de async/await y entendimiento de promesas.

¡Saludos!

2024-05-06 17:14 UTC, merged