Oswaldo mendez 1127060867
julian-vargas-kambcode/modulo3-kambcode pull request #8
Opened 2024-04-12 18:02 UTC by oswaldo-mendez

cambios

2024-04-12 21:14 UTC, julian-vargas-kambcode commented
Bien hecho oswaldo mejoraste el resultado sin embargo modificaste el readme externo pro favor dejalo igual al original para poder hacer merge a tu rama correctamente.

2024-04-12 21:46 UTC, julian-vargas-kambcode requested changes
Hola Oswaldo, este archivo deberia estar en la raiz del proyecto, al interior de tu carpeta debes poner tu archivo README.md propio y el de la raiz dejarlo como estan en la rama main

2024-04-12 21:47 UTC, julian-vargas-kambcode requested changes
Hola Oswaldo, este archivo deberia estar en la raiz del proyecto, al interior de tu carpeta debes poner tu archivo README.md propio y el de la raiz dejarlo como estan en la rama main

2024-04-13 01:12 UTC, oswaldo-mendez commented
hola Julián ya realice cambios estuve chachareando un poco para salir de dudas y genere muchos cambios pero ya detecte mi falla

2024-04-15 19:44 UTC, julian-vargas-kambcode approved these changes

2024-04-15 19:44 UTC, julian-vargas-kambcode commented
Gracias por completar tu trabajo. lo hiciste bien.

2024-04-15 19:44 UTC, merged